#version 450

layout(binding = 0) uniform sampler2D inputImage;
layout(binding = 1)buffer OutputBuffer {
    uvec4 data[];
} outputbuffer;

layout(local_size_x = 4, local_size_y = 4) in;

// 声明共享内存
shared uvec4 shared_rgba_Color[4 * 4];//4*4个像素
shared uvec4 shared_ucolor_inter[4];//插值颜色 rgba8u
shared uint shared_ualpha_inter[8];//插值alpha
shared uvec4 shared_outputbuffer;//输出共享缓冲区

// 计算工作组内存的索引,计算全局内存的索引
ivec2 globalcoords = ivec2(gl_GlobalInvocationID.xy);
ivec2 localcoords = ivec2(gl_LocalInvocationID.xy);
uvec2 workGroupID = ivec2(gl_WorkGroupID.xy);
ivec2 imgSize = textureSize(inputImage, 0);
int localIndex = int(localcoords.y * 4 + localcoords.x);
int globalIndex = globalcoords.y * imgSize.x + globalcoords.x; 

//生成rgba8u的颜色块
uvec4 get_rgba8u(vec4 color)
{
	vec4 adjustedColor = max(color, vec4(1.0 / 255.0));
	vec4 highPrecisionColor = adjustedColor * 255.0;
	uvec4 ucolor = uvec4(roundEven(highPrecisionColor));
	return ucolor;
}

//rgba8u转换rgb565u
uvec3 rgba8u_to_rgb565u(uvec4 rgba8u)
{
	uvec3 rgb565u;
    rgb565u.r = (rgba8u.r & 0xF8);
    rgb565u.g = (rgba8u.g & 0xFC);
    rgb565u.b = (rgba8u.b & 0xF8);
    return rgb565u;
}

//计算两个颜色的距离
uint color_distance(uvec4 color1, uvec4 color2)
{
	uint r = color1.r > color2.r ? color1.r - color2.r : color2.r - color1.r;
    uint g = color1.g > color2.g ? color1.g - color2.g : color2.g - color1.g;
    uint b = color1.b > color2.b ? color1.b - color2.b : color2.b - color1.b;
    return r + g + b;
}

//计算两个alpha距离
uint alpha_distance(uint alpha1, uint alpha2)
{
	return alpha1 > alpha2 ? alpha1 - alpha2 : alpha2 - alpha1;
}

//更新插值颜色及alpha
void update_inter_color(uvec4 rgba8ucolor)
{
	// 初始化插值颜色
    shared_ucolor_inter[0] = uvec4(255, 255, 255, 255);
    shared_ucolor_inter[1] = uvec4(0, 0, 0, 0);
    barrier();

    // 更新插值颜色 color0 color1 及 alpha0 alpha1
    atomicMax(shared_ucolor_inter[1].r, rgba8ucolor.r);
    atomicMax(shared_ucolor_inter[1].g, rgba8ucolor.g);
    atomicMax(shared_ucolor_inter[1].b, rgba8ucolor.b);
    atomicMax(shared_ucolor_inter[1].a, rgba8ucolor.a);

    atomicMin(shared_ucolor_inter[0].r, rgba8ucolor.r);
    atomicMin(shared_ucolor_inter[0].g, rgba8ucolor.g);
    atomicMin(shared_ucolor_inter[0].b, rgba8ucolor.b);
    atomicMin(shared_ucolor_inter[0].a, rgba8ucolor.a);
    barrier();

    // 更新插值颜色 color2 color3, 更新插值 alpha0 alpha1
    if (localcoords == ivec2(0, 0)) { // 工作组内仅一个线程更新
        shared_ucolor_inter[2] = 2 * shared_ucolor_inter[0] / 3 + shared_ucolor_inter[1] / 3;
        shared_ucolor_inter[3] = shared_ucolor_inter[0] / 3 + 2 * shared_ucolor_inter[1] / 3;
        shared_ualpha_inter[0] = shared_ucolor_inter[0].a;
        shared_ualpha_inter[1] = shared_ucolor_inter[1].a;
    } else if (localcoords == ivec2(0, 1)) { // 工作组内仅一个线程更新
        // 更新 alpha
        if (shared_ualpha_inter[0] > shared_ualpha_inter[1]) {
            // 6 interpolated alpha values
            shared_ualpha_inter[2] = 6 * shared_ucolor_inter[0].a / 7 + shared_ucolor_inter[1].a / 7;
            shared_ualpha_inter[3] = 5 * shared_ucolor_inter[0].a / 7 + 2 * shared_ucolor_inter[1].a / 7;
            shared_ualpha_inter[4] = 4 * shared_ucolor_inter[0].a / 7 + 3 * shared_ucolor_inter[1].a / 7;
            shared_ualpha_inter[5] = 3 * shared_ucolor_inter[0].a / 7 + 4 * shared_ucolor_inter[1].a / 7;
            shared_ualpha_inter[6] = 2 * shared_ucolor_inter[0].a / 7 + 5 * shared_ucolor_inter[1].a / 7;
            shared_ualpha_inter[7] = shared_ucolor_inter[0].a / 7 + 6 * shared_ucolor_inter[1].a / 7;
        } else {
            // 4 interpolated alpha values
            shared_ualpha_inter[2] = 4 * shared_ucolor_inter[0].a / 5 + shared_ucolor_inter[1].a / 5;
            shared_ualpha_inter[3] = 3 * shared_ucolor_inter[0].a / 5 + 2 * shared_ucolor_inter[1].a / 5;
            shared_ualpha_inter[4] = 2 * shared_ucolor_inter[0].a / 5 + 3 * shared_ucolor_inter[1].a / 5;
            shared_ualpha_inter[5] = shared_ucolor_inter[0].a / 5 + 4 * shared_ucolor_inter[1].a / 5;
            shared_ualpha_inter[6] = 0;
            shared_ualpha_inter[7] = 255;
        }
    }
    barrier();
}

//计算alpha索引
uint get_alpha_index(uint alpha)
{
    int index;
    uint min_distance = 255;
    for(int i = 0;i < 8;i++)
	{
        uint tem_distance = alpha_distance(alpha, shared_ualpha_inter[i]);
		if(tem_distance < min_distance)
		{
			min_distance = tem_distance;
            index = i;
		}
	}
    return index;
}

//计算颜色索引
uint get_color_index(uvec4 color)
{
	int index;
	uint min_distance = 255;
	for(int i = 0;i < 4;i++)
	{
		uint tem_distance = color_distance(color, shared_ucolor_inter[i]);
		if(tem_distance < min_distance)
		{
			min_distance = tem_distance;
			index = i;
		}
	}
	return index;
}

//填充shareoutputbuffer
void update_shared_outputbuffer()
{
    //插值颜色及插值alpha
	if(localcoords == ivec2(0, 0))//工作组内仅一个线程更新
    {
        shared_outputbuffer.a = (shared_ualpha_inter[0] << 24) | (shared_ualpha_inter[1] << 16);
        
        uvec3 rgb565ucolor0 = rgba8u_to_rgb565u(shared_ucolor_inter[0]);
        uvec3 rgb565ucolor1 = rgba8u_to_rgb565u(shared_ucolor_inter[1]);
        uint rgb565ucolorint0 = rgb565ucolor0.r | (rgb565ucolor0.g << 5) | (rgb565ucolor0.b << 11);
        uint rgb565ucolorint1 = rgb565ucolor1.r | (rgb565ucolor1.g << 5) | (rgb565ucolor1.b << 11);
        shared_outputbuffer.g = rgb565ucolorint1 | (rgb565ucolorint0 << 16);
    }
    barrier();

    //更新alpha索引
    uint alpha_idx = get_alpha_index(shared_rgba_Color[localIndex].a);
    if(localIndex == 3)//更新alpha3
	{
        //更新.a部分
		uint value = alpha_idx >> 1;
		// 使用原子或更新共享变量的特定位
        atomicOr(shared_outputbuffer.a, value);

        //更新.b部分
		value = alpha_idx << 30;
        atomicOr(shared_outputbuffer.b, value);
	}
	else if(localIndex < 3)
	{
		uint value = alpha_idx << (3 * 8 + localIndex * 3);
        atomicOr(shared_outputbuffer.b, value);
	}
    else if(localIndex > 3 && localIndex < 8)
	{
		uint value = alpha_idx << (2 + 3 * (localIndex - 4));
        atomicOr(shared_outputbuffer.a, value);
	}
    else if(localIndex > 8)
	{
		uint value = alpha_idx << (3 * (localIndex - 8));
        atomicOr(shared_outputbuffer.b, value);
	}

    //更新颜色索引
    uint color_idx = get_color_index(shared_rgba_Color[localIndex]);
    atomicOr(shared_outputbuffer.r, color_idx << (localIndex * 2));
}

void main()
{
    // 将像素坐标转换为归一化坐标
    vec2 texCoords = vec2(globalcoords) / vec2(imgSize);

    //读取当前像素颜色
    vec4 color = texture(inputImage, texCoords);
    uvec4 rgba8ucolor = get_rgba8u(color);

    //更新共享urgba颜色
    shared_rgba_Color[localIndex] = rgba8ucolor;
    barrier();

    //更新插值颜色
    update_inter_color(rgba8ucolor);
    //更新共享输出缓冲区
    update_shared_outputbuffer();

    // 将浮点颜色转换为rgba8u颜色,将颜色值写入共享内存
    //shared_rgba_Color[localIndex] = rgba8ucolor;
    

    //将rgba8u颜色转换为rgb565u颜色
    //uvec3 rgb565ucolor = rgba8u_to_rgb565u(rgba8ucolor);
    // 生成一个32位的颜色值
    //uint packedColor = rgb565ucolor.r | (rgb565ucolor.g  << 8) | (rgb565ucolor.b << 16) | (rgba8ucolor.a << 24);

    
    // 将共享内存的数据写入全局内存
    //outputbuffer.data[globalIndex].r = packedColor;
    barrier();
    if (localcoords == ivec2(3, 3)) { // 工作组内仅一个线程更新
        uint workGroupIndex = workGroupID.x + workGroupID.y * gl_NumWorkGroups.x;
        outputbuffer.data[workGroupIndex] = shared_outputbuffer;
    }
    //outputbuffer.data[globalIndex] = rgba8ucolor;
    //outputbuffer.data[globalIndex] = uvec4(0xb3ef1588,0x8c278caf,0x94bb0fb1,0x0fb746f0);
}