#version 450

layout(binding = 0, rgba8) uniform image2D inputImage;
layout(binding = 1) buffer OutputBuffer {
    uint data[];
} outputbuffer;

layout(local_size_x = 16, local_size_y = 16) in;

// 声明共享内存
shared uint sharedData[16 * 16];

void main()
{
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
    vec4 color = imageLoad(inputImage, coords);
    uvec4 ucolor = uvec4(color * 255.0); // 将颜色转换为无符号整数

    // 将 uvec4 转换为 uint
    uint packedColor = (ucolor.r & 0xFF) |
                       ((ucolor.g & 0xFF) << 8) |
                       ((ucolor.b & 0xFF) << 16) |
                       ((ucolor.a & 0xFF) << 24);

    // 计算共享内存的索引
    int localIndex = int(gl_LocalInvocationID.y * 16 + gl_LocalInvocationID.x);

    // 将数据写入共享内存
    sharedData[localIndex] = packedColor;

    // 添加内存屏障，确保写操作完成
    //memoryBarrierShared();
    //barrier();

    // 获取图像的宽度和高度
    ivec2 imgSize = imageSize(inputImage);
    int globalIndex = coords.y * imgSize.x + coords.x; // 计算全局内存的索引

    // 将共享内存的数据写入全局内存
    outputbuffer.data[globalIndex] = sharedData[localIndex];
}